[package]
name = "tax"
version = "0.1.0"
authors = ["Michael Sproul <micsproul@gmail.com>"]
edition = "2018"

[dependencies]
csv = "1"
serde = "1"
serde_derive = "1"
reqwest = "0.9"
itertools = "0.8"
chrono = "0.4"
